USE [DW]
GO
/****** Object:  Table [dbo].[Fact_sslpdt]    Script Date: 07/24/2017 14:43:43 ******/
DROP TABLE [dbo].[Fact_sslpdt]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Fact_sslpdt](
	[sd_class] [char](1) NOT NULL,
	[sd_slip_fg] [char](1) NOT NULL,
	[sd_date] [datetime] NULL,
	[sp_pdate] [datetime] NULL,
	[sd_no] [nvarchar](10) NULL,
	[sd_ctno] [nvarchar](10) NULL,
	[sd_skno] [nvarchar](30) NULL,
	[sd_name] [nvarchar](60) NULL,
	[sd_whno] [nchar](10) NULL,
	[sd_whno2] [nchar](10) NULL,
	[sd_qty] [decimal](20, 6) NULL,
	[sd_price] [decimal](20, 6) NULL,
	[sd_dis] [decimal](20, 6) NULL,
	[sd_stot] [decimal](20, 6) NULL,
	[sd_spec] [nchar](20) NULL,
	[sd_rem] [varchar](255) NULL,
	[sd_unit] [nchar](8) NULL,
	[sd_unit_fg] [bit] NOT NULL,
	[sd_ave_p] [decimal](20, 6) NULL,
	[sd_pave_p] [decimal](20, 6) NULL,
	[sd_rate] [decimal](20, 6) NULL,
	[sd_val1] [decimal](20, 6) NULL,
	[sd_val2] [decimal](20, 6) NULL,
	[sd_rqty] [decimal](20, 6) NULL,
	[sd_nqty] [decimal](20, 6) NULL,
	[sd_bmno] [nchar](10) NULL,
	[sd_nokind] [bit] NOT NULL,
	[sd_sekind] [bit] NOT NULL,
	[sd_ordno] [nchar](16) NULL,
	[sd_postfg] [bit] NOT NULL,
	[sd_acspseq] [decimal](20, 6) NULL,
	[sd_csno] [nchar](20) NULL,
	[sd_csrec] [decimal](20, 6) NULL,
	[sd_sendfg] [bit] NOT NULL,
	[sd_mafkd] [int] NULL,
	[sd_mave_p] [decimal](20, 6) NULL,
	[sd_mstot] [decimal](20, 6) NULL,
	[sd_adjkd] [int] NULL,
	[sd_surefg] [bit] NOT NULL,
	[sd_seqfld] [decimal](28, 0) NULL,
	[sd_lotno] [nchar](30) NULL,
	[Chg_sp_sales] [nvarchar](10) NULL,
	[Chg_sales_Name] [nvarchar](10) NULL,
	[ct_sales] [nvarchar](10) NULL,
	[Chg_ct_sales_Name] [nvarchar](10) NULL,
	[Chg_ct_name] [nvarchar](60) NULL,
	[Chg_ct_sname] [nvarchar](12) NULL,
	[Chg_sd_whno_name] [nvarchar](30) NULL,
	[Chg_sd_class] [nvarchar](255) NULL,
	[Chg_sd_slip_fg] [nvarchar](255) NULL,
	[Chg_sd_qty] [decimal](20, 6) NOT NULL,
	[Chg_sd_sale_qty] [decimal](20, 6) NOT NULL,
	[Chg_sd_ret_qty] [decimal](20, 6) NOT NULL,
	[Chg_sd_stot] [decimal](38, 9) NULL,
	[Chg_sd_ave_p] [decimal](38, 9) NULL,
	[Chg_sale_Month_Master] [varchar](1) NOT NULL,
	[Chg_sale_Month_MasterName] [nvarchar](255) NULL,
	[Chg_inv_Month_Master] [varchar](1) NOT NULL,
	[Chg_inv_Month_MasterName] [nvarchar](255) NULL,
	[Chg_sd_sale_overmid_tot] [decimal](38, 9) NULL,
	[Chg_sd_sale_overmid_dis] [decimal](38, 9) NULL,
	[Chg_sd_sale_oversmall_tot] [decimal](38, 9) NULL,
	[Chg_sd_sale_oversmall_dis] [decimal](38, 9) NULL,
	[Chg_sd_price] [decimal](38, 9) NULL,
	[Chg_sd_price_tax] [decimal](18, 4) NULL,
	[Chg_sd_stot_tax] [decimal](18, 4) NULL,
	[Chg_sd_tax] [decimal](18, 4) NULL,
	[Chg_Low_sd_price] [decimal](21, 6) NULL,
	[Chg_Cost_stot] [decimal](38, 6) NULL,
	[Chg_Profit] [decimal](38, 6) NULL,
	[Chg_Profit_Rate] [decimal](38, 6) NULL,
	[Chg_save_stot] [decimal](38, 9) NULL,
	[Chg_sd_dis_avg] [decimal](38, 9) NULL,
	[Chg_sd_dis_rate] [decimal](18, 4) NULL,
	[Chg_SP_Pay_Rate] [decimal](38, 6) NULL,
	[Chg_sd_Pay_Sale] [decimal](18, 4) NULL,
	[Chg_sd_Pay_Profit] [decimal](18, 4) NULL,
	[###sslip###] [varchar](13) NOT NULL,
	[Chg_sp_ave_p] [decimal](20, 6) NULL,
	[Chg_sp_mave_p] [decimal](20, 6) NULL,
	[Chg_SP_Sale_Tot] [decimal](38, 9) NULL,
	[Chg_SP_Ret_Tot] [decimal](38, 9) NULL,
	[Chg_sp_tax] [decimal](38, 6) NULL,
	[Chg_sp_dis] [decimal](38, 6) NULL,
	[Chg_sp_dis_tax] [numeric](38, 6) NULL,
	[Chg_sp_dis_flg] [varchar](2) NOT NULL,
	[Chg_sp_dis2] [decimal](38, 6) NULL,
	[Chg_sp_dis_tax2] [decimal](38, 6) NULL,
	[Chg_sp_dis_tot2] [decimal](38, 6) NULL,
	[Chg_sp_sum_tot] [decimal](38, 9) NULL,
	[Chg_Non_SP_Pay] [decimal](38, 9) NULL,
	[Chg_SP_PAMT] [decimal](38, 9) NULL,
	[Chg_SP_MAMT] [decimal](38, 9) NULL,
	[Chg_sp_slip_name] [nvarchar](12) NULL,
	[Chg_sp_date_Year] [int] NULL,
	[Chg_sp_date_Quarter] [int] NULL,
	[Chg_sp_date_Month] [int] NULL,
	[Chg_sp_date_YearWeek] [int] NULL,
	[Chg_sp_date_YM] [varchar](10) NULL,
	[Chg_sp_date_MD] [varchar](10) NULL,
	[Chg_sp_date_Weekno] [int] NULL,
	[Chg_sp_date_Weekname] [varchar](4) NULL,
	[Chg_sp_date_Week_Range] [varchar](30) NULL,
	[Chg_sp_pdate_Year] [int] NULL,
	[Chg_sp_pdate_Quarter] [int] NULL,
	[Chg_sp_pdate_Month] [int] NULL,
	[Chg_sp_pdate_YearWeek] [int] NULL,
	[Chg_sp_pdate_YM] [varchar](10) NULL,
	[Chg_sp_pdate_MD] [varchar](10) NULL,
	[Chg_sp_pdate_Weekno] [int] NULL,
	[Chg_sp_pdate_Weekname] [varchar](4) NULL,
	[Chg_sp_pdate_Week_Range] [varchar](30) NULL,
	[sp_maker] [nvarchar](10) NULL,
	[sp_rem] [varchar](100) NULL,
	[Chg_Logistics_Rej_flg] [nvarchar](255) NOT NULL,
	[Chg_Logistics_Rej_sp_name] [varchar](6) NULL,
	[Chg_Logistics_Rej_sp_no] [varchar](20) NOT NULL,
	[Chg_Logistics_Rej_sp_date] [datetime] NULL,
	[Chg_Logistics_Rej_sp_ctno] [nvarchar](10) NULL,
	[Chg_Logistics_Rej_sp_ctname] [nvarchar](60) NULL,
	[###pemploy###] [varchar](15) NOT NULL,
	[sp_sales] [nvarchar](10) NULL,
	[sp_sales_name] [nvarchar](10) NULL,
	[ct_class] [char](1) NULL,
	[sp_ctno] [nvarchar](10) NULL,
	[ct_no8] [nvarchar](8) NULL,
	[ct_sname8] [nvarchar](121) NULL,
	[sp_ctname] [nvarchar](60) NULL,
	[ct_sname] [nvarchar](12) NULL,
	[ct_fld3] [nvarchar](60) NULL,
	[e_dept] [nchar](8) NULL,
	[Chg_sp_dp_Name] [nvarchar](20) NULL,
	[Chg_dp_name] [nvarchar](20) NULL,
	[ct_loc] [nchar](10) NULL,
	[Chg_loc_Name] [nvarchar](40) NULL,
	[Chg_ctno_CustKind_CustCity] [nvarchar](255) NULL,
	[Chg_ctno_CustChain] [nvarchar](255) NULL,
	[Chg_busine_Name] [nvarchar](40) NULL,
	[ct_sour] [nchar](10) NULL,
	[Chg_sour_Name] [nvarchar](40) NULL,
	[Chg_ctno_Port_Office] [nvarchar](255) NULL,
	[ct_kind] [nchar](10) NULL,
	[Chg_ctclass] [varchar](4) NULL,
	[sp_mstno] [nchar](10) NULL,
	[Chg_sp_mst_name] [nchar](80) NULL,
	[###pcust###] [varchar](13) NOT NULL,
	[Chg_Cust_Sale_Class] [nvarchar](1) NULL,
	[Chg_Cust_Sale_Class_Name] [varchar](9) NULL,
	[Chg_Cust_Sale_Class_sName] [nvarchar](4000) NULL,
	[chg_ct_close] [varchar](1) NULL,
	[Chg_IS_Lan_Custom] [varchar](1) NULL,
	[Chg_BU_NO] [nvarchar](6) NULL,
	[Chg_ct_fld3] [nvarchar](60) NULL,
	[Chg_Hunderd_Customer] [varchar](1) NULL,
	[Chg_Hunderd_Customer_Name] [nvarchar](255) NULL,
	[Chg_CTNO_Last_Order_Flag] [varchar](1) NOT NULL,
	[Chg_BUNO_Last_Order_Flag] [varchar](1) NOT NULL,
	[###sstock###] [varchar](14) NOT NULL,
	[sk_bcode] [nvarchar](30) NULL,
	[sk_kind] [nchar](8) NULL,
	[sk_ivkd] [nchar](8) NULL,
	[sk_spec] [nvarchar](20) NULL,
	[sk_unit] [nvarchar](8) NULL,
	[sk_color] [nvarchar](20) NULL,
	[sk_size] [nvarchar](10) NULL,
	[sk_use] [nvarchar](10) NULL,
	[sk_aux_q] [decimal](20, 6) NULL,
	[sk_aux_u] [nchar](8) NULL,
	[sk_save] [decimal](20, 6) NULL,
	[sk_bqty] [decimal](20, 6) NULL,
	[sk_fign] [nchar](60) NULL,
	[sk_pic] [nvarchar](4000) NULL,
	[sk_tfg] [char](1) NULL,
	[st_cspes] [varchar](255) NULL,
	[st_espes] [varchar](255) NULL,
	[st_unit] [nchar](8) NULL,
	[st_inerqty] [decimal](20, 6) NULL,
	[st_inerunt] [nchar](8) NULL,
	[st_outqty] [decimal](20, 6) NULL,
	[st_outunt] [nchar](8) NULL,
	[st_appr] [decimal](20, 6) NULL,
	[st_apprunt] [nchar](5) NULL,
	[st_nw] [decimal](20, 6) NULL,
	[st_gw] [decimal](20, 6) NULL,
	[st_gwunt] [nchar](10) NULL,
	[st_itclass] [nchar](16) NULL,
	[st_cccode] [nchar](15) NULL,
	[st_sespes] [nchar](60) NULL,
	[st_20cyqty] [decimal](20, 6) NULL,
	[st_40cyqty] [decimal](20, 6) NULL,
	[st_45cyqty] [decimal](20, 6) NULL,
	[sk_fld1] [nvarchar](60) NULL,
	[sk_fld2] [nvarchar](60) NULL,
	[sk_fld3] [nvarchar](60) NULL,
	[sk_fld4] [nvarchar](60) NULL,
	[sk_fld5] [nvarchar](60) NULL,
	[sk_fld6] [nvarchar](60) NULL,
	[sk_fld11] [nvarchar](60) NULL,
	[sk_fld12] [nvarchar](60) NULL,
	[sk_ikind] [decimal](20, 6) NULL,
	[s_supp] [nchar](10) NULL,
	[s_locate] [nchar](10) NULL,
	[s_price1] [decimal](20, 6) NULL,
	[s_price2] [decimal](20, 6) NULL,
	[s_price3] [decimal](20, 6) NULL,
	[s_price4] [decimal](20, 6) NULL,
	[s_price5] [decimal](20, 6) NULL,
	[s_price6] [decimal](20, 6) NULL,
	[s_aprice] [decimal](20, 6) NULL,
	[s_m_ave] [decimal](20, 6) NULL,
	[s_updat1] [datetime] NULL,
	[s_updat2] [datetime] NULL,
	[s_lprice1] [decimal](20, 6) NULL,
	[s_lprice2] [decimal](20, 6) NULL,
	[s_accno1] [nchar](10) NULL,
	[sk_nowqty] [decimal](20, 6) NULL,
	[st_proven] [nchar](1) NULL,
	[st_lenght] [decimal](20, 6) NULL,
	[st_width] [decimal](20, 6) NULL,
	[st_height] [decimal](20, 6) NULL,
	[st_lwhunit] [nchar](8) NULL,
	[st_unw] [decimal](20, 6) NULL,
	[st_ugw] [decimal](20, 6) NULL,
	[st_uappr] [decimal](20, 6) NULL,
	[st_uarea] [decimal](20, 6) NULL,
	[st_areaunt] [nchar](8) NULL,
	[st_fign2] [nchar](60) NULL,
	[st_fign3] [nchar](60) NULL,
	[st_fign4] [nchar](60) NULL,
	[sk_poseq] [int] NULL,
	[sk_abcode] [nchar](30) NULL,
	[s_apice2] [decimal](20, 6) NULL,
	[s_apice3] [decimal](20, 6) NULL,
	[s_apice4] [decimal](20, 6) NULL,
	[s_apice5] [decimal](20, 6) NULL,
	[s_apice6] [decimal](20, 6) NULL,
	[sk_whno] [nvarchar](10) NULL,
	[Chg_skno_accno] [nvarchar](1) NULL,
	[Chg_skno_accno_Name] [nvarchar](255) NULL,
	[Chg_skno_BKind] [nvarchar](2) NULL,
	[Chg_skno_Bkind_Name] [nvarchar](255) NULL,
	[Chg_skno_BKind2] [nvarchar](2) NULL,
	[Chg_skno_Bkind_Name2] [nvarchar](255) NULL,
	[Chg_skno_SKind] [nvarchar](4) NULL,
	[Chg_skno_SKind_Name] [nvarchar](255) NULL,
	[Chg_kind_Name] [nchar](30) NULL,
	[Chg_ivkd_Name] [nchar](30) NULL,
	[Chg_StartYear] [nvarchar](4) NULL,
	[Chg_StartMonth] [nvarchar](2) NULL,
	[Chg_EndYear] [nvarchar](4) NULL,
	[Chg_EndMonth] [nvarchar](2) NULL,
	[Chg_supp_Name] [nchar](60) NULL,
	[Chg_supp_SName] [nchar](12) NULL,
	[Chg_locate_MArea] [nvarchar](1) NULL,
	[Chg_locate_DArea] [nvarchar](2) NULL,
	[Chg_locate_row] [nvarchar](1) NULL,
	[Chg_locate_col] [nvarchar](1) NULL,
	[Chg_updat1_Year] [int] NULL,
	[Chg_updat1_Month] [int] NULL,
	[Chg_updat2_Year] [int] NULL,
	[Chg_updat2_Month] [int] NULL,
	[Chg_New_Arrival_Date] [datetime] NULL,
	[Chg_IS_New_Stock] [varchar](1) NOT NULL,
	[Chg_New_First_Qty] [float] NULL,
	[Chg_Stock_NonSales] [varchar](1) NULL,
	[chg_new_arrival_ym] [varchar](7) NULL,
	[###sware###] [varchar](13) NOT NULL,
	[Chg_WD_AA_sQty] [decimal](20, 6) NULL,
	[Chg_WD_AA_first_Qty] [decimal](20, 6) NULL,
	[Chg_WD_AA_first_diff_Qty] [decimal](21, 6) NULL,
	[Chg_WD_AA_last_Qty] [decimal](32, 6) NULL,
	[Chg_WD_AA_last_diff_Qty] [decimal](32, 6) NULL,
	[Chg_WD_AB_sQty] [decimal](20, 6) NULL,
	[Chg_WD_AB_first_Qty] [decimal](20, 6) NULL,
	[Chg_WD_AB_first_diff_Qty] [decimal](21, 6) NULL,
	[Chg_WD_AB_last_Qty] [decimal](32, 6) NULL,
	[Chg_WD_AB_last_diff_Qty] [decimal](32, 6) NULL,
	[Chg_WD_AC_sQty] [decimal](20, 6) NULL,
	[Chg_WD_AC_first_Qty] [decimal](20, 6) NULL,
	[Chg_WD_AC_first_diff_Qty] [decimal](21, 6) NULL,
	[Chg_WD_AC_last_Qty] [decimal](32, 6) NULL,
	[Chg_WD_AC_last_diff_Qty] [decimal](32, 6) NULL,
	[Chg_WD_AG_sQty] [decimal](20, 6) NULL,
	[Chg_WD_AG_first_Qty] [decimal](20, 6) NULL,
	[Chg_WD_AG_first_diff_Qty] [decimal](21, 6) NULL,
	[Chg_WD_AG_last_Qty] [decimal](32, 6) NULL,
	[Chg_WD_AG_last_diff_Qty] [decimal](32, 6) NULL,
	[Chg_IS_Dead_Stock] [varchar](1) NULL,
	[Chg_Dead_First_Qty] [float] NULL,
	[Chg_Dead_First_Amt] [float] NULL,
	[Chg_Dead_Stock_YM] [varchar](7) NULL,
	[Chg_Dept_Cust_Chain_No] [nvarchar](10) NULL,
	[Chg_Dept_Cust_Chain_Name] [nvarchar](30) NULL,
	[sslpdt_update_datetime] [datetime] NOT NULL,
	[sslpdt_timestamp] [binary](8) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
