USE [DW]
GO
/****** Object:  Table [dbo].[Fact_sstock]    Script Date: 07/24/2017 14:43:43 ******/
DROP TABLE [dbo].[Fact_sstock]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Fact_sstock](
	[sk_no] [nvarchar](30) NULL,
	[sk_bcode] [nvarchar](30) NULL,
	[sk_name] [nvarchar](60) NULL,
	[sk_kind] [nchar](8) NULL,
	[sk_ivkd] [nchar](8) NULL,
	[sk_spec] [nvarchar](20) NULL,
	[sk_unit] [nvarchar](8) NULL,
	[sk_color] [nvarchar](20) NULL,
	[sk_use] [nvarchar](10) NULL,
	[sk_aux_q] [decimal](20, 6) NULL,
	[sk_aux_u] [nchar](8) NULL,
	[sk_size] [nvarchar](10) NULL,
	[sk_save] [decimal](20, 6) NULL,
	[sk_bqty] [decimal](20, 6) NULL,
	[sk_rem] [varchar](255) NULL,
	[sk_fign] [nchar](60) NULL,
	[sk_pic] [nvarchar](4000) NULL,
	[sk_tfg] [char](1) NULL,
	[st_cspes] [varchar](255) NULL,
	[st_espes] [varchar](255) NULL,
	[st_unit] [nchar](8) NULL,
	[st_inerqty] [decimal](20, 6) NULL,
	[st_inerunt] [nchar](8) NULL,
	[st_outqty] [decimal](20, 6) NULL,
	[st_outunt] [nchar](8) NULL,
	[st_appr] [decimal](20, 6) NULL,
	[st_apprunt] [nchar](5) NULL,
	[st_nw] [decimal](20, 6) NULL,
	[st_gw] [decimal](20, 6) NULL,
	[st_gwunt] [nchar](10) NULL,
	[st_itclass] [nchar](16) NULL,
	[st_cccode] [nchar](15) NULL,
	[st_sespes] [nchar](60) NULL,
	[st_20cyqty] [decimal](20, 6) NULL,
	[st_40cyqty] [decimal](20, 6) NULL,
	[st_45cyqty] [decimal](20, 6) NULL,
	[sk_fld1] [nvarchar](60) NULL,
	[sk_fld2] [nvarchar](60) NULL,
	[sk_fld3] [nvarchar](60) NULL,
	[sk_fld4] [nvarchar](60) NULL,
	[sk_fld5] [nvarchar](60) NULL,
	[sk_fld6] [nvarchar](60) NULL,
	[sk_fld7] [nvarchar](60) NULL,
	[sk_fld8] [nvarchar](60) NULL,
	[sk_fld9] [nvarchar](60) NULL,
	[sk_fld10] [nvarchar](60) NULL,
	[sk_fld11] [nvarchar](60) NULL,
	[sk_fld12] [nvarchar](60) NULL,
	[sk_ltime] [decimal](20, 6) NULL,
	[sk_ikind] [decimal](20, 6) NULL,
	[s_supp] [nchar](10) NULL,
	[s_locate] [nchar](10) NULL,
	[s_price1] [decimal](20, 6) NULL,
	[s_price2] [decimal](20, 6) NULL,
	[s_price3] [decimal](20, 6) NULL,
	[s_price4] [decimal](20, 6) NULL,
	[s_price5] [decimal](20, 6) NULL,
	[s_price6] [decimal](20, 6) NULL,
	[s_aprice] [decimal](20, 6) NULL,
	[s_m_ave] [decimal](20, 6) NULL,
	[s_updat1] [datetime] NULL,
	[s_updat2] [datetime] NULL,
	[s_lprice1] [decimal](20, 6) NULL,
	[s_lprice2] [decimal](20, 6) NULL,
	[s_accno1] [nchar](10) NULL,
	[s_accno2] [nchar](10) NULL,
	[s_accno3] [nchar](10) NULL,
	[s_accno4] [nchar](10) NULL,
	[s_accno5] [nchar](10) NULL,
	[s_accno6] [nchar](10) NULL,
	[st_jname] [nchar](60) NULL,
	[st_jspes] [varchar](255) NULL,
	[sk_nowqty] [decimal](20, 6) NULL,
	[st_proven] [nchar](1) NULL,
	[st_lenght] [decimal](20, 6) NULL,
	[st_width] [decimal](20, 6) NULL,
	[st_height] [decimal](20, 6) NULL,
	[st_lwhunit] [nchar](8) NULL,
	[st_unw] [decimal](20, 6) NULL,
	[st_ugw] [decimal](20, 6) NULL,
	[st_uappr] [decimal](20, 6) NULL,
	[st_uarea] [decimal](20, 6) NULL,
	[st_areaunt] [nchar](8) NULL,
	[st_freno] [nchar](10) NULL,
	[st_fign2] [nchar](60) NULL,
	[st_fign3] [nchar](60) NULL,
	[st_fign4] [nchar](60) NULL,
	[sk_poseq] [int] NULL,
	[sk_abcode] [nchar](30) NULL,
	[s_apice2] [decimal](20, 6) NULL,
	[s_apice3] [decimal](20, 6) NULL,
	[s_apice4] [decimal](20, 6) NULL,
	[s_apice5] [decimal](20, 6) NULL,
	[s_apice6] [decimal](20, 6) NULL,
	[sk_wfno] [nchar](30) NULL,
	[sk_whno] [nvarchar](10) NULL,
	[sk_mdpfg] [char](1) NULL,
	[sk_lotfg] [bit] NOT NULL,
	[Chg_skno_accno] [nvarchar](1) NOT NULL,
	[Chg_skno_accno_Name] [nvarchar](255) NOT NULL,
	[Chg_skno_BKind] [nvarchar](2) NOT NULL,
	[Chg_skno_Bkind_Name] [nvarchar](255) NOT NULL,
	[Chg_skno_BKind2] [nvarchar](2) NOT NULL,
	[Chg_skno_Bkind_Name2] [nvarchar](255) NOT NULL,
	[Chg_skno_BKind3] [varchar](2) NOT NULL,
	[Chg_skno_Bkind_Name3] [varchar](4) NOT NULL,
	[Chg_skno_SKind] [nvarchar](4) NULL,
	[Chg_skno_SKind_Name] [nvarchar](255) NULL,
	[Chg_kind_Name] [nchar](30) NULL,
	[Chg_ivkd_Name] [nchar](30) NULL,
	[Chg_StartYear] [nvarchar](4) NULL,
	[Chg_StartMonth] [nvarchar](2) NULL,
	[Chg_EndYear] [nvarchar](4) NULL,
	[Chg_EndMonth] [nvarchar](2) NULL,
	[Chg_supp_Name] [nchar](60) NULL,
	[Chg_supp_SName] [nchar](12) NULL,
	[Chg_locate_MArea] [nvarchar](1) NULL,
	[Chg_locate_DArea] [nvarchar](2) NULL,
	[Chg_locate_row] [nvarchar](1) NULL,
	[Chg_locate_col] [nvarchar](1) NULL,
	[Chg_updat1_Year] [int] NULL,
	[Chg_updat1_Month] [int] NULL,
	[Chg_updat2_Year] [int] NULL,
	[Chg_updat2_Month] [int] NULL,
	[Chg_Stock_NonSales] [varchar](1) NOT NULL,
	[Chg_WD_AA_sQty] [decimal](20, 6) NOT NULL,
	[Chg_WD_AA_first_Qty] [decimal](20, 6) NOT NULL,
	[Chg_WD_AA_first_diff_Qty] [decimal](21, 6) NOT NULL,
	[Chg_WD_AA_last_Qty] [decimal](32, 6) NOT NULL,
	[Chg_WD_AA_last_diff_Qty] [decimal](32, 6) NOT NULL,
	[Chg_WD_AB_sQty] [decimal](20, 6) NOT NULL,
	[Chg_WD_AB_first_Qty] [decimal](20, 6) NOT NULL,
	[Chg_WD_AB_first_diff_Qty] [decimal](21, 6) NOT NULL,
	[Chg_WD_AB_last_Qty] [decimal](32, 6) NOT NULL,
	[Chg_WD_AB_last_diff_Qty] [decimal](32, 6) NOT NULL,
	[Chg_WD_AC_sQty] [decimal](20, 6) NOT NULL,
	[Chg_WD_AC_first_Qty] [decimal](20, 6) NOT NULL,
	[Chg_WD_AC_first_diff_Qty] [decimal](21, 6) NOT NULL,
	[Chg_WD_AC_last_Qty] [decimal](32, 6) NOT NULL,
	[Chg_WD_AC_last_diff_Qty] [decimal](32, 6) NOT NULL,
	[Chg_WD_AG_sQty] [decimal](20, 6) NOT NULL,
	[Chg_WD_AG_first_Qty] [decimal](20, 6) NOT NULL,
	[Chg_WD_AG_first_diff_Qty] [decimal](21, 6) NOT NULL,
	[Chg_WD_AG_last_Qty] [decimal](32, 6) NOT NULL,
	[Chg_WD_AG_last_diff_Qty] [decimal](32, 6) NOT NULL,
	[Chg_IS_Dead_Stock] [varchar](1) NOT NULL,
	[Chg_Dead_First_Qty] [float] NOT NULL,
	[Chg_Dead_First_Amt] [float] NOT NULL,
	[Chg_Dead_Stock_YM] [varchar](7) NULL,
	[Chg_New_Arrival_Date] [datetime] NULL,
	[Chg_New_Arrival_YM] [varchar](7) NULL,
	[Chg_New_First_Qty] [float] NOT NULL,
	[Chg_color] [nvarchar](255) NULL,
	[Chg_size] [nvarchar](255) NULL,
	[Chg_package] [nvarchar](255) NULL,
	[Chg_barcode_name] [nvarchar](255) NULL,
	[Chg_price] [nvarchar](255) NULL,
	[Chg_pic_6] [nvarchar](255) NULL,
	[Chg_pic_4] [nvarchar](255) NULL,
	[Chg_pic_2] [nvarchar](255) NULL,
	[Chg_main_pic] [nvarchar](255) NULL,
	[Chg_pic1] [nvarchar](255) NULL,
	[Chg_pic2] [nvarchar](255) NULL,
	[Chg_pic3] [nvarchar](255) NULL,
	[Chg_avg_price] [nvarchar](255) NULL,
	[Chg_product_property] [nvarchar](255) NULL,
	[Chg_gross_property] [nvarchar](255) NULL,
	[sstock_update_datetime] [datetime] NOT NULL,
	[sstock_Timestamp] [binary](8) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
