USE [DW]
GO
/****** Object:  Table [dbo].[TB_Config]    Script Date: 07/24/2017 14:43:54 ******/
DROP TABLE [dbo].[TB_Config]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TB_Config](
	[Kind] [varchar](4) NOT NULL,
	[Kind_Name] [varchar](100) NULL,
	[Flag] [int] NULL,
	[Value] [varchar](1000) NULL,
PRIMARY KEY CLUSTERED 
(
	[Kind] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
