USE [DW]
GO
/****** Object:  Table [dbo].[Fact_pcust]    Script Date: 07/24/2017 14:43:43 ******/
DROP TABLE [dbo].[Fact_pcust]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Fact_pcust](
	[ct_class] [char](1) NULL,
	[ct_no] [nvarchar](10) NULL,
	[ct_name] [nvarchar](60) NULL,
	[ct_sname] [nvarchar](12) NULL,
	[ct_no8] [nvarchar](8) NULL,
	[ct_sname8] [nvarchar](121) NULL,
	[ct_addr1] [varchar](255) NULL,
	[ct_addr2] [varchar](255) NULL,
	[ct_addr3] [varchar](255) NULL,
	[ct_tel] [nvarchar](35) NULL,
	[ct_fax] [nvarchar](20) NULL,
	[ct_unino] [nvarchar](10) NULL,
	[ct_presid] [nvarchar](40) NULL,
	[ct_contact] [nvarchar](40) NULL,
	[ct_payfg] [char](1) NULL,
	[ct_sales] [nvarchar](10) NULL,
	[ct_p_limit] [decimal](20, 6) NULL,
	[ct_b_limit] [decimal](20, 6) NULL,
	[ct_bkno] [nvarchar](20) NULL,
	[ct_bknm] [nvarchar](50) NULL,
	[ct_rem] [varchar](255) NULL,
	[ct_dept] [nvarchar](8) NULL,
	[ct_payrate] [int] NULL,
	[ct_ivtitle] [nvarchar](60) NULL,
	[ct_porter] [nvarchar](10) NULL,
	[ct_credit] [nvarchar](10) NULL,
	[ct_pmode] [char](1) NULL,
	[ct_pdate] [int] NULL,
	[ct_prenpay] [decimal](20, 6) NULL,
	[ct_prepay] [decimal](20, 6) NULL,
	[ct_last_dt] [datetime] NULL,
	[ct_flg] [bit] NOT NULL,
	[ct_t_fg] [bit] NOT NULL,
	[ct_grade] [char](2) NULL,
	[ct_area] [char](3) NULL,
	[ct_curt_id] [nvarchar](8) NULL,
	[ct_cont_sp] [nvarchar](20) NULL,
	[ct_pay] [nchar](8) NULL,
	[ct_regist] [nvarchar](14) NULL,
	[ct_worker] [decimal](20, 6) NULL,
	[ct_capital] [nchar](30) NULL,
	[ct_skpay] [decimal](20, 6) NULL,
	[ct_sknpay] [decimal](20, 6) NULL,
	[ct_accno2] [nchar](8) NULL,
	[ct_chkno2] [nchar](8) NULL,
	[ct_cdate] [datetime] NULL,
	[ct_payer] [nchar](10) NULL,
	[ct_advance] [decimal](20, 6) NULL,
	[ct_debt] [decimal](20, 6) NULL,
	[ct_abroad] [decimal](20, 6) NULL,
	[ct_fld1] [nvarchar](60) NULL,
	[ct_fld2] [nvarchar](60) NULL,
	[ct_fld3] [nvarchar](60) NULL,
	[ct_fld4] [nvarchar](60) NULL,
	[ct_fld5] [nvarchar](60) NULL,
	[ct_fld6] [nvarchar](60) NULL,
	[ct_fld7] [nvarchar](60) NULL,
	[ct_fld8] [nvarchar](60) NULL,
	[ct_fld9] [nvarchar](60) NULL,
	[ct_fld10] [nvarchar](60) NULL,
	[ct_fld11] [nvarchar](60) NULL,
	[ct_fld12] [nvarchar](60) NULL,
	[ct_sea] [nchar](20) NULL,
	[ct_invofg] [char](1) NULL,
	[ct_udec] [decimal](20, 6) NULL,
	[ct_tdec] [decimal](20, 6) NULL,
	[ct_busine] [nchar](20) NULL,
	[ct_banpay] [nvarchar](20) NULL,
	[ct_loc] [nchar](10) NULL,
	[ct_sour] [nchar](10) NULL,
	[ct_kind] [nchar](10) NULL,
	[ct_tkday] [int] NULL,
	[Chg_ctclass] [varchar](4) NULL,
	[Chg_BU_NO] [nvarchar](6) NULL,
	[Chg_Is_BU] [varchar](1) NOT NULL,
	[Chg_ctno_Port_Office] [nvarchar](255) NULL,
	[Chg_ctno_CustKind_CustCity] [nvarchar](255) NULL,
	[Chg_ctno_CustChain] [nvarchar](255) NULL,
	[Chg_ct_dept_Name] [nvarchar](20) NULL,
	[Chg_ct_sales_Name] [nvarchar](10) NULL,
	[Chg_credit_Name] [nvarchar](12) NULL,
	[Chg_busine_Name] [nvarchar](40) NULL,
	[Chg_loc_Name] [nvarchar](40) NULL,
	[Chg_sour_Name] [nvarchar](40) NULL,
	[Chg_Customer_kind_Name] [nvarchar](40) NULL,
	[Chg_payfg_Name] [nvarchar](255) NULL,
	[Chg_porter_Name] [nvarchar](30) NULL,
	[Chg_pmode_Name] [nvarchar](255) NULL,
	[Chg_fld1_Year] [nvarchar](4) NULL,
	[Chg_fld1_Month] [nvarchar](2) NULL,
	[Chg_fld2_Year] [nvarchar](4) NULL,
	[Chg_fld2_Month] [nvarchar](2) NULL,
	[Chg_Hunderd_Customer] [varchar](1) NOT NULL,
	[Chg_Hunderd_Customer_Name] [nvarchar](255) NULL,
	[Chg_IS_Lan_Custom] [varchar](1) NOT NULL,
	[Chg_ct_close] [varchar](1) NOT NULL,
	[Chg_rate_date] [datetime] NULL,
	[Chg_rate] [decimal](20, 6) NULL,
	[Chg_Cust_Sale_Class] [nvarchar](1) NULL,
	[Chg_Cust_Sale_Class_Name] [varchar](9) NOT NULL,
	[Chg_Cust_Sale_Class_sName] [nvarchar](4000) NULL,
	[Chg_Cust_Dis_Mapping] [varchar](1) NOT NULL,
	[pcust_update_datetime] [datetime] NOT NULL,
	[pcust_timestamp] [binary](8) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
